version: '3.4'

services:
  mysql:
    image: mysql:8.0
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
    networks: 
      - backend-network
    restart: always
  
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    environment: 
      # - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    networks: 
      - backend-network
      - frontend-network
    restart: always
    depends_on: 
      - mysql

  wordpress:
    image: bitnami/wordpress:6.4.3
    environment:
      - WORDPRESS_DATABASE_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DATABASE_USER=${MYSQL_USER}
      - WORDPRESS_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DATABASE_HOST=mysql
      - WORDPRESS_ENABLE_HTTPS=yes
    volumes:
      - wordpress_data:/var/www/html
    networks: 
      - backend-network
      - frontend-network
    restart: always
    depends_on: 
      - mysql

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: '${DOMAIN} -> http://wordpress:8080'
      STAGE: 'production' 
    networks:
      - frontend-network

volumes:
  mysql_data:
  wordpress_data:

networks: 
  backend-network:
  frontend-network:
